import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// export const metadata = {
//   title: "Blog App",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.ico", // Default Favicon
//     apple: "/apple-touch-icon.png", // Apple Touch Icon
//     shortcut: "/favicon.png", // Alternative Shortcut Icon
//   },
// };

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
  icons: {
    icon: "https://fav.farm/📓", // External favicon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
